/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#dee5ff",
        "surface-bright": "#1f2b49",
        "secondary-dim": "#ccd5e4",
        "surface-container": "#0f1930",
        "primary-container": "#00f1fe",
        "on-secondary-container": "#c8d1e0",
        "on-primary": "#005f64",
        "primary": "#99f7ff",
        "surface-container-low": "#091328",
        "inverse-primary": "#006a70",
        "primary-fixed-dim": "#00e2ee",
        "surface-container-highest": "#192540",
        "primary-dim": "#00e2ee",
        "background": "#060e20",
        "on-tertiary-fixed-variant": "#4700a7",
        "on-error": "#490006",
        "on-surface": "#dee5ff",
        "primary-fixed": "#00f1fe",
        "error": "#ff716c",
        "inverse-surface": "#faf8ff",
        "inverse-on-surface": "#4d556b",
        "secondary-fixed-dim": "#ccd5e4",
        "error-dim": "#d7383b",
        "tertiary-fixed-dim": "#b190ff",
        "secondary": "#dae3f2",
        "tertiary-fixed": "#bda1ff",
        "outline-variant": "#40485d",
        "secondary-fixed": "#dae3f2",
        "on-tertiary-container": "#f8f1ff",
        "surface": "#060e20",
        "secondary-container": "#3e4754",
        "outline": "#6d758c",
        "tertiary": "#ac89ff",
        "tertiary-dim": "#874cff",
        "surface-container-high": "#141f38",
        "on-primary-fixed": "#004145",
        "on-tertiary-fixed": "#1f0052",
        "on-primary-container": "#00555a",
        "error-container": "#9f0519",
        "on-error-container": "#ffa8a3",
        "on-tertiary": "#290067",
        "surface-container-lowest": "#000000",
        "on-secondary": "#49525f",
        "on-primary-fixed-variant": "#006065",
        "tertiary-container": "#7000ff",
        "on-secondary-fixed-variant": "#535c69",
        "surface-tint": "#99f7ff",
        "surface-variant": "#192540",
        "on-surface-variant": "#a3aac4",
        "on-secondary-fixed": "#37404c",
        "surface-dim": "#060e20"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}
